# Generated by Django 4.1 on 2022-08-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stay_sharp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="All_knifes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=15)),
                ("series", models.CharField(max_length=15)),
                ("steel", models.CharField(max_length=10)),
                ("carbon", models.FloatField()),
                ("CrMoV", models.FloatField()),
                ("angle", models.FloatField()),
                ("honing_add", models.FloatField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("low_quality", "low-quality"),
                            ("medium_quality", "medium-quality"),
                            ("high_quality", "high-quality"),
                            ("high_quality", "high-quality"),
                        ],
                        default="low_quality",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="All_knife",),
    ]
