# Generated by Django 4.1 on 2022-08-22 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stay_sharp", "0003_alter_all_knifes_crmov_alter_all_knifes_angle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="all_knifes",
            name="CrMoV",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(50),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="all_knifes",
            name="angle",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(40),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="all_knifes",
            name="brand",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="all_knifes",
            name="carbon",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="all_knifes",
            name="honing_add",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="all_knifes",
            name="series",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="all_knifes",
            name="steel",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
