# Generated by Django 4.1 on 2022-08-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stay_sharp", "0006_alter_all_knifes_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="all_knifes",
            name="category",
            field=models.CharField(
                choices=[
                    ("low_quality", "low_quality"),
                    ("medium_quality", "medium_quality"),
                    ("high_quality", "high_quality"),
                    ("premium_quality", "premium_quality"),
                ],
                default="low_quality",
                max_length=20,
            ),
        ),
    ]
