# Generated by Django 4.1 on 2022-08-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stay_sharp", "0011_alter_all_knifes_brend_alter_all_knifes_series_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="all_knifes",
            name="brand",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="all_knifes",
            name="series",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="all_knifes",
            name="steel",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
