# Generated by Django 4.1 on 2022-09-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stay_sharp", "0014_grinding_data_honing_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grinding_data", name="C1", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="grinding_data", name="C2", field=models.FloatField(),
        ),
    ]
