# Generated by Django 4.1 on 2022-09-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stay_sharp", "0015_alter_grinding_data_c1_alter_grinding_data_c2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grinding_data",
            name="C1",
            field=models.FloatField(default=50.0),
        ),
        migrations.AlterField(
            model_name="grinding_data",
            name="C2",
            field=models.FloatField(default=28.6),
        ),
    ]
