# Generated by Django 4.1 on 2022-09-10 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stay_sharp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stay_sharp", "0017_account_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="all_knifes",
            name="user",
            field=models.OneToOneField(
                default=stay_sharp.models.get_superuser,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
