# Generated by Django 4.1 on 2022-09-12 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stay_sharp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stay_sharp", "0019_alter_all_knifes_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="all_knifes", name="user",),
        migrations.AddField(
            model_name="account_table",
            name="user",
            field=models.ForeignKey(
                default=stay_sharp.models.get_superuser,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="account_table",
            name="comments",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
