# Generated by Django 4.1 on 2022-09-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stay_sharp", "0020_remove_all_knifes_user_account_table_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account_table",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
