# Generated by Django 4.1 on 2022-09-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stay_sharp", "0021_alter_account_table_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account_table",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
