# Generated by Django 4.1 on 2022-09-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "stay_sharp",
            "0023_alter_account_table_crmov_alter_account_table_brend_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="account_table",
            name="date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
