# Generated by Django 4.0.8 on 2022-10-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info_cheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_visit', models.DateField()),
                ('visitor', models.CharField(max_length=20)),
                ('IP_of_visitor', models.GenericIPAddressField()),
                ('email_of_visitor', models.EmailField(max_length=254)),
                ('choose_visits', models.BooleanField(default=False)),
                ('calculation_visits', models.BooleanField(default=False)),
                ('account_table_visits', models.BooleanField(default=False)),
            ],
        ),
    ]
