# Generated by Django 4.0.8 on 2022-10-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_ss', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info_cheet',
            old_name='IP_of_visitor',
            new_name='visitor_IP',
        ),
        migrations.RenameField(
            model_name='info_cheet',
            old_name='email_of_visitor',
            new_name='visitor_email',
        ),
        migrations.RenameField(
            model_name='info_cheet',
            old_name='visitor',
            new_name='visitor_id',
        ),
        migrations.AddField(
            model_name='info_cheet',
            name='visitor_name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
