# Generated by Django 4.0.8 on 2022-10-13 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_ss', '0002_rename_ip_of_visitor_info_cheet_visitor_ip_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info_cheet',
            new_name='Info_table',
        ),
    ]
