# Generated by Django 4.0.8 on 2022-10-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_ss', '0003_rename_info_cheet_info_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_table',
            name='visitor_tz',
            field=models.CharField(default='', max_length=10),
        ),
    ]
