# Generated by Django 4.0.8 on 2022-10-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_ss', '0004_info_table_visitor_tz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_table',
            name='date_of_visit',
            field=models.DateTimeField(),
        ),
    ]
